'use strict';
const C=window.COURSE,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved={};try{saved=JSON.parse(localStorage.getItem('sdi-study-v1')||'{}')||{}}catch(e){}
let chapter=C.chapters.find(c=>c.id===Number(saved.chapter))||C.chapters[0],view='learn',query='',scope='chapter',practiceFilter='chapter';
const source=c=>`assets/chap-${c.id<=11?'1-11':'12-28'}.pdf`;
const math=t=>`<div class="math">\\[${esc(t)}\\]</div>`;
function persist(){saved.chapter=chapter.id;try{localStorage.setItem('sdi-study-v1',JSON.stringify(saved))}catch(e){}}
function typeset(){if(window.MathJax?.typesetPromise)window.MathJax.typesetPromise([$('#content')]).catch(()=>{});}
function progress(){const done=C.questions.filter(q=>saved[q.id]?.status==='done').length;$('#progress').textContent=`${done} / 56 bài đã đánh dấu hiểu`;$('#bar').style.width=`${done/56*100}%`;}
function nav(){const q=normalize($('#chapter-search').value);$('#chapters').innerHTML=C.chapters.filter(c=>normalize(`${c.id} ${c.title}`).includes(q)).map(c=>`<button data-chapter="${c.id}" class="${c.id===chapter.id?'selected':''}" ${c.id===chapter.id?'aria-current="page"':''}><span>${String(c.id).padStart(2,'0')}</span><span>${esc(c.title)}</span></button>`).join('');progress();}
function normalize(t){return String(t).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();}
function formula(f,c,showChapter=false){return `<article class="card"><span class="badge ${f.kind==='Tài liệu'?'':'add'}">${esc(f.kind)}</span>${showChapter?` <span class="muted">Chương ${c.id}</span>`:''}<h3>${esc(f.name)}</h3>${math(f.tex)}<p class="condition">${esc(f.condition)}</p>${showChapter?`<button data-jump="${c.id}">Học chương ${c.id}</button>`:''}</article>`;}
function bridge(key){const b=C.bridges[key];return `<article class="card"><span class="badge add">Kiến thức liên hệ</span><h3>${esc(b.title)}</h3>${math(b.tex)}<p>${esc(b.explanation)}</p><p class="bridge-origin">${esc(b.origin)}</p></article>`;}
function learn(){const qs=C.questions.filter(q=>q.chapter===chapter.id);return `<article class="card lesson-points"><span class="badge">Ý chính cần nắm</span><h2>Hiểu trước khi thay số</h2>${chapter.concepts.map(p=>`<p>${esc(p)}</p>`).join('')}<div class="callout"><strong>Chỗ dễ nhầm</strong>${esc(chapter.mistake)}</div><div class="actions"><button class="primary" data-view="practice">Luyện ${qs.length} bài của chương</button><button data-view="source">Đọc đầy đủ bản gốc · trang ${chapter.page}–${chapter.end}</button></div></article><div class="section-title"><h2>Công thức của chương</h2><span class="muted">${chapter.formulas.length} thẻ</span></div><div class="grid">${chapter.formulas.map(f=>formula(f,chapter)).join('')}</div><div class="section-title"><h2>Cần nhớ từ kiến thức khác</h2></div><p class="jump">Các công cụ dưới đây giúp nối dữ kiện bài tập với công thức của chương.</p><div class="grid">${chapter.links.map(bridge).join('')}</div>`;}
function formulas(){const cs=scope==='all'?C.chapters:[chapter];const matches=cs.flatMap(c=>c.formulas.map(f=>({f,c}))).filter(({f,c})=>normalize(`${f.name} ${f.tex} ${f.condition} ${c.title} ${f.kind}`).includes(normalize(query)));return `<div class="toolbar"><input id="formula-search" type="search" aria-label="Tìm công thức" placeholder="Tìm: RC, năng lượng, MOSFET…" value="${esc(query)}"><select id="formula-scope" aria-label="Phạm vi tra cứu"><option value="chapter" ${scope==='chapter'?'selected':''}>Chương đang học</option><option value="all" ${scope==='all'?'selected':''}>Tất cả 28 chương</option></select></div><p class="muted">${matches.length} công thức. “Tài liệu”: công thức từ PDF; “Suy ra”: biến đổi từ kiến thức đã học; “Bổ sung”: công cụ hoặc mô hình thêm để giải bài.</p><div class="grid" id="formula-results">${matches.map(({f,c})=>formula(f,c,scope==='all')).join('')||'<p class="empty">Không có công thức phù hợp. Hãy thử từ khóa khác.</p>'}</div>`;}
function exercise(q){const st=saved[q.id]||{},ch=C.chapters[q.chapter-1];return `<article class="card exercise" id="q-${q.id}"><span class="badge">Bài ${q.id} · Chương ${q.chapter}</span><span class="status"> ${st.status==='done'?'✓ Đã hiểu':st.status==='review'?'↻ Cần ôn lại':''}</span><h2>${esc(q.title)}</h2><p class="prompt">${esc(q.prompt)}</p><details><summary>Cần nhớ trước khi giải</summary><p class="muted">${esc(ch.mistake)}</p>${ch.formulas.map(f=>`<p><strong>${esc(f.name)}</strong></p>${math(f.tex)}<p class="condition">${esc(f.condition)}</p>`).join('')}${ch.links.map(bridge).join('')}</details><label for="note-${q.id}">Cách giải của bạn</label><textarea id="note-${q.id}" data-note="${q.id}" placeholder="Ghi dữ kiện, công thức, đổi đơn vị và lập luận…">${esc(st.note||'')}</textarea>${q.fields.length?`<div class="fields">${q.fields.map((f,i)=>`<label for="field-${q.id}-${i}">${esc(f.label)} (${esc(f.unit)})<input id="field-${q.id}-${i}" data-field="${q.id}" data-index="${i}" inputmode="decimal" placeholder="Ví dụ: 1.2e-3" value="${esc(st.values?.[i]||'')}"></label>`).join('')}</div><p class="muted">Nhập theo đơn vị ghi bên trên; có thể dùng dấu phẩy thập phân hoặc dạng 1.2e-3. Chấp nhận sai số làm tròn 1%. Kiểm tra số không đánh giá phần giải thích hoặc chiều vectơ.</p><button class="primary" data-check="${q.id}">Kiểm tra kết quả số</button>`:'<p class="muted">Bài này cần lập luận. Viết lời giải rồi tự đối chiếu với đáp án bên dưới.</p>'}<div id="feedback-${q.id}" role="status"></div><details><summary>Gợi ý bước đầu</summary><p>${esc(q.steps[0]||'Nhận dạng mô hình và liệt kê dữ kiện trước khi tính.')}</p></details><details><summary>Xem lời giải và đáp án</summary><ol>${q.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="callout"><strong>Đáp án</strong>${esc(q.answer)}</div><div class="actions"><button data-status="done" data-q="${q.id}">✓ Tôi đã hiểu bài này</button><button data-status="review" data-q="${q.id}">↻ Cần ôn lại</button></div></details></article>`;}
function practice(){let qs=C.questions.filter(q=>practiceFilter==='all'||(practiceFilter==='review'?saved[q.id]?.status==='review':q.chapter===chapter.id));return `<div class="toolbar"><select id="practice-filter" aria-label="Chọn bài luyện"><option value="chapter" ${practiceFilter==='chapter'?'selected':''}>Bài của chương ${chapter.id}</option><option value="all" ${practiceFilter==='all'?'selected':''}>Tất cả 56 bài tự luyện</option><option value="review" ${practiceFilter==='review'?'selected':''}>Bài đánh dấu cần ôn lại</option></select><button id="random">Chọn ngẫu nhiên một bài</button></div><p class="muted">${qs.length} bài • Đề và đáp án dựa trên tài liệu; lời giải từng bước được biên soạn thêm. Hãy tự giải trước khi mở đáp án.</p>${qs.map(exercise).join('')||'<div class="card empty">Chưa có bài cần ôn lại. Mở lời giải của một bài và đánh dấu “Cần ôn lại”.</div>'}`;}
function bridges(){return `<article class="card"><h2>Kết nối kiến thức để giải bài</h2><p>Công thức của một chương thường cần thêm công cụ từ hình học, vectơ, bảo toàn năng lượng, logarit hoặc mô hình của chương khác. Mỗi mục ghi cách dùng và nguồn gốc của phần bổ sung.</p></article><div class="section-title"><h2>Liên quan đến chương ${chapter.id}</h2></div><div class="grid">${chapter.links.map(bridge).join('')}</div><details class="card"><summary><strong>Mở toàn bộ ${Object.keys(C.bridges).length} mục kiến thức nền</strong></summary><div class="grid" style="margin-top:20px">${Object.keys(C.bridges).filter(k=>!chapter.links.includes(k)).map(bridge).join('')}</div></details>`;}
function sources(){const file=source(chapter);const ex=C.examples.filter(e=>e.chapter===chapter.id);return `<article class="card"><h2>Đọc nguyên bản & bài mẫu</h2><p>Toàn bộ 82 trang của hai PDF được giữ lại để tra cứu ký hiệu, bảng và các lập luận đầy đủ. Có 70 bài mẫu trong bản gốc và 56 bài tự luyện ở phần luyện bài.</p><div class="source-links"><a href="assets/chap-1-11.pdf" target="_blank" rel="noopener">PDF chương 1–11 · 39 trang</a><a href="assets/chap-12-28.pdf" target="_blank" rel="noopener">PDF chương 12–28 · 43 trang</a></div><p class="muted">Chương ${chapter.id}: trang PDF ${chapter.page}–${chapter.end}. Số trang dưới đây tính từ đầu tệp, bao gồm bìa và mục lục.</p><div class="examples"><button data-page="${chapter.page}">Lý thuyết & công thức chương ${chapter.id}</button>${ex.map(e=>`<button data-page="${e.page}">Bài mẫu ${esc(e.id)} · ${esc(e.title)} · trang ${e.page}</button>`).join('')}</div><p><a id="pdf-new" href="${file}#page=${chapter.page}" target="_blank" rel="noopener">Mở chương đang học ở tab mới ↗</a></p><iframe class="source-view" id="pdf-view" src="${file}#page=${chapter.page}" title="Tài liệu gốc chương ${chapter.id}"></iframe><p class="muted">Nếu trình duyệt điện thoại không hiển thị PDF, hãy mở liên kết ở tab mới hoặc tải PDF.</p></article><article class="card"><h2>Quy ước và tài liệu đối chiếu</h2><p>Các thẻ là phần hệ thống hóa để học nhanh; bản PDF chứa toàn bộ bài gốc. Luôn đọc điều kiện áp dụng. Hằng số và đơn vị có thể dùng hai hệ khác nhau ở phần vật lý và bán dẫn (m⁻³ / cm⁻³); không trộn đơn vị.</p><p>Phần bổ sung dùng các mô hình chuẩn: hình học và đại số, phương trình chuyển động, bảo toàn năng lượng, mạch bậc một, tiếp giáp p–n và MOS. Các mô hình bán dẫn là các gần đúng có điều kiện, không phải quan hệ đúng với mọi linh kiện.</p><ul><li><a target="_blank" rel="noopener" href="https://openstax.org/books/university-physics-volume-2/pages/8-1-capacitors-and-capacitance">OpenStax · Điện dung</a></li><li><a target="_blank" rel="noopener" href="https://openstax.org/books/university-physics-volume-2/pages/16-1-maxwells-equations-and-electromagnetic-waves">OpenStax · Maxwell và sóng điện từ</a></li><li><a target="_blank" rel="noopener" href="https://www.chu.berkeley.edu/modern-semiconductor-devices-for-integrated-circuits-chenming-calvin-hu-2010/">Chenming Hu · Modern Semiconductor Devices for Integrated Circuits</a></li></ul></article>`;}
function render(){if(window.MathJax?.typesetClear)window.MathJax.typesetClear([$('#content')]);$('#chapter-number').textContent=`CHƯƠNG ${String(chapter.id).padStart(2,'0')} / 28`;$('#chapter-title').textContent=chapter.title;$('#chapter-meta').textContent=`${chapter.id<=11?'Nền tảng điện và từ':'Vật liệu, bán dẫn và mạch điện tử'} · ${chapter.formulas.length} công thức · 2 bài tự luyện`;document.querySelectorAll('.tabs button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view))});$('#content').innerHTML=({learn,formulas,practice,bridges,source:sources}[view])();nav();typeset();persist();}
function choose(n){chapter=C.chapters.find(c=>c.id===Number(n))||chapter;query='';practiceFilter='chapter';$('#sidebar').classList.remove('open');$('#menu').setAttribute('aria-expanded','false');render();window.scrollTo({top:0,behavior:'smooth'});}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.chapter)choose(b.dataset.chapter);else if(b.dataset.jump){view='learn';choose(b.dataset.jump)}else if(b.dataset.view){view=b.dataset.view;render()}else if(b.dataset.page){const url=source(chapter)+'#page='+b.dataset.page;$('#pdf-view').src=url;$('#pdf-new').href=url;$('#pdf-view').scrollIntoView({behavior:'smooth',block:'start'})}else if(b.dataset.check){check(b.dataset.check)}else if(b.dataset.status){const id=b.dataset.q;saved[id]={...saved[id],status:b.dataset.status};persist();b.closest('.exercise').querySelector('.status').textContent=b.dataset.status==='done'?'✓ Đã hiểu':'↻ Cần ôn lại';progress()}else if(b.id==='random'){const pool=practiceFilter==='review'?C.questions.filter(q=>saved[q.id]?.status==='review'):C.questions;if(!pool.length)return;const q=pool[Math.floor(Math.random()*pool.length)];practiceFilter='all';render();$('#q-'+q.id).scrollIntoView({behavior:'smooth',block:'start'})}else if(b.id==='menu'){const open=$('#sidebar').classList.toggle('open');b.setAttribute('aria-expanded',String(open));}});
document.addEventListener('input',e=>{const el=e.target;if(el.id==='chapter-search')nav();else if(el.id==='formula-search'){query=el.value;const pos=el.selectionStart;render();$('#formula-search').focus();$('#formula-search').setSelectionRange(pos,pos)}else if(el.dataset.note){const id=el.dataset.note;saved[id]={...saved[id],note:el.value};persist()}else if(el.dataset.field){const id=el.dataset.field;const values=saved[id]?.values||[];values[el.dataset.index]=el.value;saved[id]={...saved[id],values};persist();}});
document.addEventListener('change',e=>{if(e.target.id==='formula-scope'){scope=e.target.value;render()}else if(e.target.id==='practice-filter'){practiceFilter=e.target.value;render()}});
function check(id){const q=C.questions.find(q=>q.id===id);const box=$('#feedback-'+id);let all=true,missing=false;const lines=q.fields.map((f,i)=>{const raw=$(`#field-${id}-${i}`).value.trim().replace(/,/g,'.').replace(/−/g,'-');if(!raw){missing=true;all=false;return `${esc(f.label)}: chưa nhập.`}const n=Number(raw);if(!Number.isFinite(n)){all=false;return `${esc(f.label)}: số chưa hợp lệ.`}const ok=Math.abs(n-f.value)<=(f.value===0?1e-12:Math.abs(f.value)*.01);if(!ok)all=false;return `${esc(f.label)}: ${ok?'✓ Kết quả phù hợp':'↻ Kiểm tra lại công thức, dấu và đơn vị'}.`});box.className='feedback '+(all?'good':'bad');box.innerHTML=`<strong>${all?'Các kết quả số phù hợp. Hãy kiểm tra thêm lập luận trước khi đánh dấu đã hiểu.':missing?'Hãy nhập đủ kết quả để kiểm tra.':'Có kết quả cần kiểm tra lại.'}</strong><br>${lines.join('<br>')}`;}
render();window.addEventListener('load',typeset);

